[tool.poetry]
name = "gravel"
version = "0.1.0"
description = ""
authors = ["Taka <amano.takahisa@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
numpy = ">=1.22"
gdal = ">=3.1.1"
affine = ">=2.3"
geopandas = ">=0.10"
matplotlib = {version = ">=3.5", optional = true }
pytest = {version = "*", optional = true }
python = ">=3.8"

[tool.poetry.extras]
plot = ["matplotlib"]
test = ["pytest", "matplotlib"]



[tool.poetry.group.dev.dependencies]
jupyterlab = "*"
typing-extensions = "*"
sphinx = '*'
sphinx-rtd-theme = '*'

[tool.black]
line-length = 79

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
