[tool.poetry]
name = "gravel"
version = "0.1.0"
description = ""
authors = ["Taka <amano.takahisa@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
affine = "^2.3.1"
gdal = ">=3.4"
geopandas = "^0.12.2"
matplotlib = {version = "^3.6.2", optional = true }
pytest = {version = "*", optional = true }
numpy = "^1.24.1"
python = ">=3.9"

[tool.poetry.extras]
plot = ["matplotlib"]
test = ["pytest", "matplotlib"]



[tool.poetry.group.dev.dependencies]
jupyterlab = "^3.5.2"
typing-extensions = "^4.4.0"

[tool.black]
line-length = 79

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
