# This is a basic workflow to help you get started with Actions

name: pytest

# Controls when the workflow will run
on:
  # Triggers this workflow on pull request events but only for the develop branch
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # runs-on: ${{ matrix.platform }}
    runs-on: ubuntu-latest
    
    # strategy:
    #  matrix:
    #    # platform: [ubuntu-latest]
    #    python-version: [3.7, 3.8, 3.9, 3.10]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Update
        run: |
          sudo apt-get update
          sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get install gdal-bin libgdal-dev
          # apt-get -y install software-properties-common
          # add-apt-repository -y ppa:deadsnakes/ppa
          # apt-get update
 
      # Setup python
      - name: Set up Python 3.8 # ${{ matrix.python-version }}
        uses: actions/setup-python@v3.0.0
        with:
          python-version: '3.8' # ${{ matrix.python-version }}
          
      # Install dependencies and the package
      - name: Install dependencies and the package
        run: |        
          # sudo apt install -y lib-dev
          # sudo apt install -y lib-dev
          python -m pip install --upgrade pip
          python -m pip install -r requirements_dev.txt
          python -m pip install -e .[test]
        
      - name: Run linter
        run: make lint
        
      - name: Run tests
        run: make test

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
