# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  Linting:
    name: Lint | pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            gdal-bin libgdal-dev
          pip install -U pip
          pip install .[test]
      - uses: pre-commit/action@v3.0.0

  Test:
    needs: Linting
    name: Test | python-${{ matrix.python-version }}, GDAL-${{ matrix.gdal-version }}
    runs-on: ubuntu-latest
    container: osgeo/gdal:ubuntu-small-${{ matrix.gdal-version }}
    strategy:
      matrix:
        python-version: ["3.8", "3.11"]
        gdal-version: ["3.1.1", "3.6.1"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install packages
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            python3-pip
          pip install -U pip
          pip install .[test,dev]

      - name: pytest
        run: |
          pytest -vvs
